#!/bin/sh

set -e

wget -nv -O /usr/bin/docker https://get.docker.com/builds/Linux/x86_64/docker-1.6.2
chmod +x /usr/bin/docker

HEKAD_VNAME=heka-$(echo ${HEKAD_VERSION} | tr . _)-linux-amd64
wget -nv -O hekad.tar.gz https://github.com/mozilla-services/heka/releases/download/v${HEKAD_VERSION}/${HEKAD_VNAME}.tar.gz
tar -zxf hekad.tar.gz
rm hekad.tar.gz
cp -r ${HEKAD_VNAME}/* /usr
rm -rf ${HEKAD_VNAME}
